Feat/sponsor component#46
polymer-day/web pull request #67
Opened 2016-09-22 21:24 UTC by jlsanchezsanz

Sponsor component and positioning styles #46

2016-09-22 21:33 UTC, jorgecasar commented
This use `iron-ajax` and mocks instead of `polymerday-data`.

Review the commits, please

2016-09-23 07:05 UTC, jorgecasar commented on src/polymerday-sponsors-list.html
> +        _titlesMap: {
This create a dependency, you don't know need to know the sponsor types. It should be a property

2016-09-23 07:07 UTC, jorgecasar commented on src/polymerday-sponsors-list.html
> +      .sponsor-platinum {
Platinum, gold, iron and paper could change and this stop working. Use a property.

2016-09-23 07:16 UTC, jorgecasar commented on src/polymerday-sponsors-list.html
>        properties: {
I guess we need this properties:

- sponsors (Array)
- header (String)
- logos-size (String): Enumerable with option like XL, L, M, S or something like this.

2016-09-23 07:23 UTC, jorgecasar commented on src/polymerday-sponsors-list.html
> +    <polymerday-data
Sorry about that, I guess it's better to take out this and avoid to create a dependency with the data access.

2016-09-23 07:25 UTC, jorgecasar requested changes

2016-09-23 14:55 UTC, jlsanchezsanz commented on src/polymerday-sponsors-list.html
> +      .sponsor-platinum {
done

2016-09-23 14:56 UTC, jlsanchezsanz commented on src/polymerday-sponsors-list.html
> +    <polymerday-data
done

2016-09-23 14:56 UTC, jlsanchezsanz commented on src/polymerday-sponsors-list.html
>        properties: {
done

2016-09-23 14:56 UTC, jlsanchezsanz commented on src/polymerday-sponsors-list.html
> +        _titlesMap: {
done

2016-09-23 16:28 UTC, jorgecasar approved these changes

2016-09-23 16:29 UTC, merged